env:
  name: redis_gym
  version: 0.0.1
  k8s: False
  max_steps: 25
  waiting_period: 5
  target_deployment: redis-leader

  actions:
    - type: do_nothing
    - type: scale_up
      replicas: 1
    - type: scale_up
      replicas: 2
    - type: scale_up
      replicas: 3
    - type: scale_up
      replicas: 4
    - type: scale_up
      replicas: 5
    - type: scale_up
      replicas: 6
    - type: scale_up
      replicas: 7
    - type: scale_down
      replicas: 1
    - type: scale_down
      replicas: 2
    - type: scale_down
      replicas: 3
    - type: scale_down
      replicas: 4
    - type: scale_down
      replicas: 5
    - type: scale_down
      replicas: 6
    - type: scale_down
      replicas: 7

deployments:
  - name: redis-leader
    type: redis
    namespace: redis
    pods:
      min: 1
      max: 8
    resources:
      limits:
        cpu: 250
        mem: 500
      requests:
        cpu: 250
        mem: 500
    scaling:
      cpu_weight: 0.7
      mem_weight: 0.3
      threshold: 0.75

  - name: redis-follower
    type: redis
    namespace: redis
    pods:
      min: 1
      max: 8
    resources:
      limits:
        cpu: 250
        mem: 500
      requests:
        cpu: 250
        mem: 500
    scaling:
      cpu_weight: 0.7
      mem_weight: 0.3
      threshold: 0.75
