kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
coreDns:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false

alertmanager:
  enabled: false
defaultRules:
  create: false

grafana:
  enabled: true
  adminPassword: gwydion
  defaultDashboardsEnabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: onlineboutique

kubelet:
  enabled: true
  serviceMonitor:
    cAdvisor: true
    resource: false
    probes: false

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: "redis"
    additionalScrapeConfigs:
      - job_name: gwydion-agent
        scrape_interval: 2s
        static_configs:
          - targets: ['host.minikube.internal:8000']
            labels:
              app: gwydion-agent